### ISSUE TITLE
Files Naming Convention

### ISSUE THREAD

**Issue by lopez-jhonlay** [PUP-BSIT/ex7-avengears#1]
all files should be named in snake case, all lower case. 
[https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g25d18931cb7_3_0](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g25d18931cb7_3_0)
@japitanajohnwalter @Malapad @JasminFerolino @ferolinojasmin @gelseykish

**Comment by Malapad** [comment]
thank you
