### ISSUE TITLE
HTML Structure: Replacing <header> to <head> element.

### ISSUE THREAD

**Issue by JonnelTocmo** [PUP-BSIT/ex7-avengears#10]
Replace "header>" with "head" for proper metadata organization

- https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Malapad_Melchorjames/Malapad_melchorjames.html#L3-L6

@Malapad

**Comment by calderonpearl** [comment]
The <head> element is a container for metadata, while the <header> element represents a container for introductory content or a set of navigational links. Kindly know their difference.

- [https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Santos_AkishaGelsey/Santos_AkishaGelsey.html#L3-L6](https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Santos_AkishaGelsey/Santos_AkishaGelsey.html#L3-L6)
- [https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Santos_AkishaGelsey/Exercise%206/Santos_AkishaGelsey.html#L3-L6](https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Santos_AkishaGelsey/Exercise%206/Santos_AkishaGelsey.html#L3-L6)
- [https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Santos_AkishaGelsey/Exercise%205/Santos_AkishaGelsey.html#L3-L4](https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Santos_AkishaGelsey/Exercise%205/Santos_AkishaGelsey.html#L3-L4)

@gelseykish

**Comment by Malapad** [comment]
thank you
