### ISSUE TITLE
Single space after selector

### ISSUE THREAD

**Issue by calderonpearl** [PUP-BSIT/ex7-avengears#11]
Add a single space after the selector/s and before "{".
[https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_35](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_35)

- [https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Santos_AkishaGelsey/style.css#L21](https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Santos_AkishaGelsey/style.css#L21)

@gelseykish

**Comment by lopez-jhonlay** [comment]
add space after selector
[https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Ferolino_Jasmin/style.css#L25](https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Ferolino_Jasmin/style.css#L25)

@ferolinojasmin @JasminFerolino
