### ISSUE TITLE
Separate every css block

### ISSUE THREAD

**Issue by Cayiee** [PUP-BSIT/ex7-avengears#2]
Separate every css block with a single space.
[https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_35](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_35)

- [https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Japitana_JohnWalter/Excercise%206/style.css](https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Japitana_JohnWalter/Excercise%206/style.css)
- [https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Japitana_JohnWalter/style.css](https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Japitana_JohnWalter/style.css)
@japitanajohnwalter

**Comment by JonnelTocmo** [comment]
- https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Malapad_Melchorjames/style.css#L1-L12

@Malapad

**Comment by calderonpearl** [comment]
Maintain putting single space per css block.
[https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_35](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_35)

- [https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Santos_AkishaGelsey/style.css#L1-L19](https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Santos_AkishaGelsey/style.css#L1-L19)

**Comment by Malapad** [comment]
thank you
