### ISSUE TITLE
Exceded 80 column 

### ISSUE THREAD

**Issue by Cayiee** [PUP-BSIT/ex7-avengears#3]
There should be max of 80 col per line. 
[https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0)

- [https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Japitana_JohnWalter/Excercise5-6.html#L12-L15](https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Japitana_JohnWalter/Excercise5-6.html#L12-L15) @japitanajohnwalter

**Comment by JonnelTocmo** [comment]
@Malapad 

https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0

https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Malapad_Melchorjames/Malapad_melchorjames.html#L13-L16

**Comment by perez-johnpatrick-m** [comment]
- [https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/index.html#L11-L14](https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/index.html#L11-L14)

@japitanajohnwalter @Malapad @ferolinojasmin @ferolinojasmin

**Comment by calderonpearl** [comment]
- [https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Santos_AkishaGelsey/Santos_AkishaGelsey.html#L13-L15](https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Santos_AkishaGelsey/Santos_AkishaGelsey.html#L13-L15)

@gelseykish

**Comment by lopez-jhonlay** [comment]
- [https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Ferolino_Jasmin/activity5.html#L36-L40](https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Ferolino_Jasmin/activity5.html#L36-L40)
- [https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Ferolino_Jasmin/Activity6.html#L15-L17](https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Ferolino_Jasmin/Activity6.html#L15-L17)
@ferolinojasmin @JasminFerolino

**Comment by Malapad** [comment]
thank you
