### ISSUE TITLE
Class Naming Convention

### ISSUE THREAD

**Issue by Cayiee** [PUP-BSIT/ex7-avengears#4]
Class names should be written in kebab case. 
[https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5)

- [https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Japitana_JohnWalter/Excercise5-6.html#L8-L9](https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Japitana_JohnWalter/Excercise5-6.html#L8-L9) @japitanajohnwalter

**Comment by JonnelTocmo** [comment]
Check the format in this presentation:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

Class names should be written in kebab case. All lower case separated by hyphen.
https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Malapad_Melchorjames/Malapad_melchorjames.html#L8-L11

Remove unnecessary spaces in the "div" element.
https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Malapad_Melchorjames/Malapad_melchorjames.html#L22
https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Malapad_Melchorjames/Malapad_melchorjames.html#L37

Missing double quote in the class attribute of the "div" element.
https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Malapad_Melchorjames/Malapad_melchorjames.html#L57

**Comment by lopez-jhonlay** [comment]
class names should be in kebab case

- [https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Ferolino_Jasmin/Activity6.html#L9-L12](https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Ferolino_Jasmin/Activity6.html#L9-L12)
@ferolinojasmin @JasminFerolino

**Comment by calderonpearl** [comment]
Class names should be written in kebab case.
[https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5)

- [https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Santos_AkishaGelsey/Santos_AkishaGelsey.html#L8-L10](https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Santos_AkishaGelsey/Santos_AkishaGelsey.html#L8-L10)

@gelseykish
