### ISSUE TITLE
Unnecessary Comments

### ISSUE THREAD

**Issue by Castillo-KrystelCaye** [PUP-BSIT/ex7-avengears#5]
Remove unnecessary comments.
[https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5)

- [https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Japitana_JohnWalter/style.css#L13](https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Japitana_JohnWalter/style.css#L13) @japitanajohnwalter

**Comment by perez-johnpatrick-m** [comment]
- [https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Japitana_JohnWalter/Excercise%206/Japitana.html#L6-L10](https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Japitana_JohnWalter/Excercise%206/Japitana.html#L6-L10)
- [https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Japitana_JohnWalter/Excercise%205/Japitana.html#L6-L10](https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Japitana_JohnWalter/Excercise%205/Japitana.html#L6-L10) @japitanajohnwalter

**Comment by perez-johnpatrick-m** [comment]
- [https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/index.html#L10](https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/index.html#L10) 
@ferolinojasmin @japitanajohnwalter @Malapad

**Comment by JonnelTocmo** [comment]
https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Malapad_Melchorjames/Malapad.html#L6

@Malapad
