### ISSUE TITLE
Tips 

### ISSUE THREAD

**Issue by perez-johnpatrick-m** [PUP-BSIT/ex7-avengears#8]
- We suggest that each member have their own folder for image assets.

**Comment by JonnelTocmo** [comment]
- Establish consistent naming conventions for Classes and IDs in your HTML and CSS.

**Comment by lopez-jhonlay** [comment]
- Install prettier extension to vscode to automatically format your code.
- Close the tag immediately so that you cant forget it.
- In html file just enter "!" on the first line. This will bring up a couple of options. Press the Enter key to choose the first one to generate html boilerplate

**Comment by Malapad** [comment]
thank you
