### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by lopez-jhonlay** [PUP-BSIT/ex7-avengears#9]
Ensure proper indentation
[https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Ferolino_Jasmin/activity5.html](https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Ferolino_Jasmin/activity5.html)
@ferolinojasmin @JasminFerolino

**Comment by JonnelTocmo** [comment]
https://github.com/PUP-BSIT/ex7-avengears/blob/61fe34db5ae0d01d8d010d01ce20995e33a95dfd/Malapad_Melchorjames/Malapad_melchorjames.html#L36-L47

@Malapad

**Comment by Malapad** [comment]
thank you
